### ISSUE TITLE
Custom Skill Tutorial Does not Work in AML

### ISSUE THREAD

**Issue by mastreips** [Azure-Samples/azure-search-python-samples#46]
I believe the files need to be updated so that it can be used in the AML environment. 

1.  git+https://github.com/NervanaSystems/nlp-architect.git@absa no longer exists (see message error below)
2.  I got a rng library error and needed to update numpy 
3. I had to use .amlignore to exempt the large model .zip file because it was too large for snapshot
4. I get a BadZipFile error that I cannot resolve (see message error below)

**Git Error:** 

Collecting git+https://github.com/NervanaSystems/nlp-architect.git@absa
  Cloning https://github.com/NervanaSystems/nlp-architect.git (to revision absa) to /tmp/pip-req-build-gn4sfh9l
  Running command git clone -q https://github.com/NervanaSystems/nlp-architect.git /tmp/pip-req-build-gn4sfh9l
  WARNING: Did not find branch or tag 'absa', assuming revision or ref.
  Running command git checkout -q absa
  error: pathspec 'absa' did not match any file(s) known to git
ERROR: Command errored out with exit status 1: git checkout -q absa Check the logs for full command output.
Note: you may need to restart the kernel to use updated packages.

**Zip File Error**

Log Output

You can now load the model via spacy.load('en')
Using pre-trained BIST model.
Downloading pre-trained BIST model...
Unable to determine total file size.
Downloading file to: /root/nlp-architect/cache/bist-pretrained/bist-pretrained.zip

0MB [00:00, ?MB/s]
1MB [00:00, 579.96MB/s]
Download Complete
Unzipping...

[2021-04-05T14:57:17.529886] The experiment failed. Finalizing run...
2021-04-05 14:57:17,535 INFO Exiting context: TrackUserError
2021-04-05 14:57:17,536 INFO Exiting context: RunHistory
Cleaning up all outstanding Run operations, waiting 900.0 seconds
1 items cleaning up...
Cleanup took 0.07420921325683594 seconds
2021-04-05 14:57:30,901 INFO Exiting context: ProjectPythonPath
Traceback (most recent call last):
File "train.py", line 46, in
max_iter=args.max_iter)
File "/azureml-envs/azureml_d664de2764d55f1b5c7b6f4fc0a2fd6b/lib/python3.6/site-packages/nlp_architect/models/absa/train/train.py", line 49, in init
self.parser = SpacyBISTParser()
File "/azureml-envs/azureml_d664de2764d55f1b5c7b6f4fc0a2fd6b/lib/python3.6/site-packages/nlp_architect/pipelines/spacy_bist.py", line 46, in init
_download_pretrained_model()
File "/azureml-envs/azureml_d664de2764d55f1b5c7b6f4fc0a2fd6b/lib/python3.6/site-packages/nlp_architect/pipelines/spacy_bist.py", line 170, in _download_pretrained_model
uncompress_file(zip_path, outpath=str(SpacyBISTParser.dir))
File "/azureml-envs/azureml_d664de2764d55f1b5c7b6f4fc0a2fd6b/lib/python3.6/site-packages/nlp_architect/utils/io.py", line 85, in uncompress_file
with zipfile.ZipFile(filepath) as z:
File "/azureml-envs/azureml_d664de2764d55f1b5c7b6f4fc0a2fd6b/lib/python3.6/zipfile.py", line 1108, in init
self._RealGetContents()
File "/azureml-envs/azureml_d664de2764d55f1b5c7b6f4fc0a2fd6b/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by HeidiSteen** [comment]
There are numerous issues with this tutorial and skill.  We've archived it until we can provide a better solution. Sorry for the churn.
